### ISSUE TITLE
关于uniformity loss

### ISSUE THREAD

**Issue by akajinchen** [CRIPAC-DIG/AUG-MAE#1]
https://github.com/AzureLeon1/AUG-MAE/blob/3361558bf0676f551d471cdec953d735240bb6d4/augmae/models/loss_func.py#L41
原文中的uniformity loss不是计算两个嵌入之间的距离吗，为什么损失是相乘呢，希望作者给予解答

**Comment by AzureLeon1** [comment]
> https://github.com/AzureLeon1/AUG-MAE/blob/3361558bf0676f551d471cdec953d735240bb6d4/augmae/models/loss_func.py#L41
> 
> 
> 原文中的uniformity loss不是计算两个嵌入之间的距离吗，为什么损失是相乘呢，希望作者给予解答

您好，因为用于计算 uniformity loss 的 feature 是经过 L2 normalization 的 (Line 32 in `augmae/models/loss_func.py`)，所以论文中 Equation 4 的指数部分可以进行如下简化：
<img src="https://latex.codecogs.com/svg.image?-t\|\boldsymbol{z}_i-\boldsymbol{z}_j\|^2=-t(\|\boldsymbol{z}_i\|^2-2\boldsymbol{z}_i^{\top}\boldsymbol{z}_j&plus;\|\boldsymbol{z}_j\|^2)=-t(2-2\boldsymbol{z}_i^{\top}\boldsymbol{z}_j)=2t(\boldsymbol{z}_i^{\top}\boldsymbol{z}_j-1)" title="-t\|\boldsymbol{z}_i-\boldsymbol{z}_j\|^2=-t(\|\boldsymbol{z}_i\|^2-2\boldsymbol{z}_i^{\top}\boldsymbol{z}_j+\|\boldsymbol{z}_j\|^2)=-t(2-2\boldsymbol{z}_i^{\top}\boldsymbol{z}_j)=2t(\boldsymbol{z}_i^{\top}\boldsymbol{z}_j-1)" />
也就是我们代码中的形式。希望能解决您的疑问。

**Comment by akajinchen** [comment]
非常感谢~

**Comment by akajinchen** [comment]
> > https://github.com/AzureLeon1/AUG-MAE/blob/3361558bf0676f551d471cdec953d735240bb6d4/augmae/models/loss_func.py#L41
> > 原文中的uniformity loss不是计算两个嵌入之间的距离吗，为什么损失是相乘呢，希望作者给予解答
> 
> 您好，因为用于计算 uniformity loss 的 feature 是经过 L2 normalization 的 (Line 32 in `augmae/models/loss_func.py`)，所以论文中 Equation 4 的指数部分可以进行如下简化： ![](https://camo.githubusercontent.com/cb27e7129eb71cd64e65531c2bbb40460d67f099f706ae4bb9a1eb78ae28661e/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f7376672e696d6167653f2d745c7c5c626f6c6473796d626f6c7b7a7d5f692d5c626f6c6473796d626f6c7b7a7d5f6a5c7c5e323d2d74285c7c5c626f6c6473796d626f6c7b7a7d5f695c7c5e322d325c626f6c6473796d626f6c7b7a7d5f695e7b5c746f707d5c626f6c6473796d626f6c7b7a7d5f6a2b5c7c5c626f6c6473796d626f6c7b7a7d5f6a5c7c5e32293d2d7428322d325c626f6c6473796d626f6c7b7a7d5f695e7b5c746f707d5c626f6c6473796d626f6c7b7a7d5f6a293d3274285c626f6c6473796d626f6c7b7a7d5f695e7b5c746f707d5c626f6c6473796d626f6c7b7a7d5f6a2d3129) 也就是我们代码中的形式。希望能解决您的疑问。

您好，为什么这里uniformity loss计算出来是负数，怎么优化呢

**Comment by AzureLeon1** [comment]
> > > https://github.com/AzureLeon1/AUG-MAE/blob/3361558bf0676f551d471cdec953d735240bb6d4/augmae/models/loss_func.py#L41
> > > 原文中的uniformity loss不是计算两个嵌入之间的距离吗，为什么损失是相乘呢，希望作者给予解答
> > 
> > 
> > 您好，因为用于计算 uniformity loss 的 feature 是经过 L2 normalization 的 (Line 32 in `augmae/models/loss_func.py`)，所以论文中 Equation 4 的指数部分可以进行如下简化： ![](https://camo.githubusercontent.com/cb27e7129eb71cd64e65531c2bbb40460d67f099f706ae4bb9a1eb78ae28661e/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f7376672e696d6167653f2d745c7c5c626f6c6473796d626f6c7b7a7d5f692d5c626f6c6473796d626f6c7b7a7d5f6a5c7c5e323d2d74285c7c5c626f6c6473796d626f6c7b7a7d5f695c7c5e322d325c626f6c6473796d626f6c7b7a7d5f695e7b5c746f707d5c626f6c6473796d626f6c7b7a7d5f6a2b5c7c5c626f6c6473796d626f6c7b7a7d5f6a5c7c5e32293d2d7428322d325c626f6c6473796d626f6c7b7a7d5f695e7b5c746f707d5c626f6c6473796d626f6c7b7a7d5f6a293d3274285c626f6c6473796d626f6c7b7a7d5f695e7b5c746f707d5c626f6c6473796d626f6c7b7a7d5f6a2d3129) 也就是我们代码中的形式。希望能解决您的疑问。
> 
> 您好，为什么这里uniformity loss计算出来是负数，怎么优化呢

loss是负数是不影响梯度下降的。这里把loss里的减一操作去掉，loss计算出来就是正数，但loss对参数的梯度还是一样的，优化效果也是一样的。

**Comment by akajinchen** [comment]
> > > > https://github.com/AzureLeon1/AUG-MAE/blob/3361558bf0676f551d471cdec953d735240bb6d4/augmae/models/loss_func.py#L41
> > > > 原文中的uniformity loss不是计算两个嵌入之间的距离吗，为什么损失是相乘呢，希望作者给予解答
> > > 
> > > 
> > > 您好，因为用于计算 uniformity loss 的 feature 是经过 L2 normalization 的 (Line 32 in `augmae/models/loss_func.py`)，所以论文中 Equation 4 的指数部分可以进行如下简化： ![](https://camo.githubusercontent.com/cb27e7129eb71cd64e65531c2bbb40460d67f099f706ae4bb9a1eb78ae28661e/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f7376672e696d6167653f2d745c7c5c626f6c6473796d626f6c7b7a7d5f692d5c626f6c6473796d626f6c7b7a7d5f6a5c7c5e323d2d74285c7c5c626f6c6473796d626f6c7b7a7d5f695c7c5e322d325c626f6c6473796d626f6c7b7a7d5f695e7b5c746f707d5c626f6c6473796d626f6c7b7a7d5f6a2b5c7c5c626f6c6473796d626f6c7b7a7d5f6a5c7c5e32293d2d7428322d325c626f6c6473796d626f6c7b7a7d5f695e7b5c746f707d5c626f6c6473796d626f6c7b7a7d5f6a293d3274285c626f6c6473796d626f6c7b7a7d5f695e7b5c746f707d5c626f6c6473796d626f6c7b7a7d5f6a2d3129) 也就是我们代码中的形式。希望能解决您的疑问。
> > 
> > 
> > 您好，为什么这里uniformity loss计算出来是负数，怎么优化呢
> 
> loss是负数是不影响梯度下降的。这里把loss里的减一操作去掉，loss计算出来就是正数，但loss对参数的梯度还是一样的，优化效果也是一样的。

我明白了 感谢指导~
